spring:
  application:
    name: multitenant
  datasource:
    password: password
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console.enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: multitenant-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${config.keycloak.server-url}/realms/${config.keycloak.realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${config.keycloak.server-url}/realms/${config.keycloak.realm}
          jwk-set-uri: ${config.keycloak.server-url}/realms/${config.keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    io.skoman: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: trace
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type: TRACE

config:
  keycloak:
    realm: multitenant-realm
    server-url: http://localhost:8081
    client-id: admin-cli
    username: superadmin
    password: superadmin

apiPrefix: /api